FROM clamav/clamav:stable

RUN apt-get update && apt-get -y install cron

COPY cron_script.sh /cron_script.sh

RUN chmod +x /cron_script.sh

RUN echo "0 0 * * * /cron_script.sh" > /etc/cron.d/clamav-update

RUN touch /var/log/cron.log

CMD ["sh", "-c", "cron && tail -f /var/log/cron.log"]
