FROM python:3.9-slim-buster

RUN apt-get update && apt-get -y install curl unzip automake libtool make gcc pkg-config wget libtool libmagic1 libgl1 libglib2.0-0 libgomp1 cron git poppler-utils libmupdf-dev net-tools 


# Download and install YARA
RUN wget https://github.com/VirusTotal/yara/archive/refs/tags/v4.4.0.tar.gz -O yara-4.4.0.tar.gz && \
    tar -zxf yara-4.4.0.tar.gz && \
    cd yara-4.4.0 && \
    ./bootstrap.sh && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf yara-4.4.0 yara-4.4.0.tar.gz

# Install ClamAV client
RUN apt-get update && \
    apt-get install -y clamdscan clamav-daemon && \
    rm -rf /var/lib/apt/lists/*

# RUN chown -R 100:101 /run/clamav
## add WORKDIR to enable reloads, uvcorn cannot reload if started from root 
WORKDIR /app

COPY requirements.txt .

RUN python -m pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install --default-timeout=10000 uvicorn[standard] gunicorn

COPY . .

EXPOSE 8000

ENV PYTHONUNBUFFERED=1

# Run the start script, it will check for an /app/devstart.sh script
CMD ["./dev_start.sh"]

